#!/usr/bin/env python3
"""Render the sealed CAPER same-source K-seed population with native V2V only.

Every cell executes the frozen Bernini-R 1.3B full-source-video ``v2v_apg``
endpoint from the existing T2V/V2V homotopy canary.  Pure T2V, homotopy,
references, first-frame anchors, target videos, custom noise, masks, tracks,
poses, flow, and trajectories are outside this runner's call graph.

The registry contains a complete 4-source x 4-seed fit population and a
separate 2-source x 2-seed lockbox.  Fit is the default/first phase.  A lockbox
cell additionally requires an explicit second-stage switch and a sealed
threshold-freeze receipt that binds the complete fit population, method
revision, registry, action taxonomy, reward thresholds, and evaluation
protocol.  The a66e stand-up item is registry-only post-hoc audit evidence and
cannot be generated by this runner.
"""

from __future__ import annotations

import argparse
from datetime import timedelta
import hashlib
import json
from pathlib import Path
import re
import sys
from typing import Any, Mapping, Optional, Sequence


METHOD_ROOT = Path(__file__).resolve().parent
if str(METHOD_ROOT) not in sys.path:
    sys.path.insert(0, str(METHOD_ROOT))

METHOD = "frozen-bernini-caper-native-full-source-v2v-kseed-population-v1"
SCHEMA_VERSION = "bernini-caper-native-kseed-cell-receipt-v1"
REGISTRY_SCHEMA_VERSION = "bernini-caper-native-kseed-population-sit-v1"
THRESHOLD_FREEZE_SCHEMA_VERSION = (
    "bernini-caper-native-kseed-threshold-freeze-v1"
)
CANONICAL_REGISTRY_RELATIVE = "assets/caper_native_kseed_population_sit_v1.json"
CANONICAL_REGISTRY_SHA256 = (
    "f700eba0d7097943a1c26d7663815a7bdfbf5cd8786c07da2189f716921a7da4"
)
ACTION_FAMILY_ID = "animal-sit-and-hold"
ACTION_TAXONOMY_SHA256 = (
    "cd25fe7e95b2d43a2b33a5b02bad44833405155c28ef2402a2b2dab11da04396"
)
FIT_SOURCE_IDS = (
    "7b88a1ca1f804f41",
    "841b5e0080a1441d",
    "402059390cdb4f50",
    "3be4072a63144b8f",
)
FIT_SEEDS = (2026081801, 2026081802, 2026081803, 2026081804)
LOCKBOX_SOURCE_IDS = ("6a7ebea80ba64f18", "ac87fea937864bd5")
LOCKBOX_SEEDS = (2026081901, 2026081902)
FIT_CELL_ORDER = tuple(
    f"fit-{source_id}-s{seed}"
    for source_id in FIT_SOURCE_IDS
    for seed in FIT_SEEDS
)
LOCKBOX_CELL_ORDER = tuple(
    f"lockbox-{source_id}-s{seed}"
    for source_id in LOCKBOX_SOURCE_IDS
    for seed in LOCKBOX_SEEDS
)
CELL_ORDER = FIT_CELL_ORDER + LOCKBOX_CELL_ORDER
FIT_CELL_IDS_SHA256 = (
    "d543d17c97c9a0090912508072c7d0c4981c7b5878fcade2d5586d4fef37e179"
)
PHASE_CELL_ORDER = {"fit": FIT_CELL_ORDER, "lockbox": LOCKBOX_CELL_ORDER}
PHASE_SOURCE_IDS = {"fit": FIT_SOURCE_IDS, "lockbox": LOCKBOX_SOURCE_IDS}
PHASE_SEEDS = {"fit": FIT_SEEDS, "lockbox": LOCKBOX_SEEDS}

NATIVE_ARM = "native-source-video-only-v2v-endpoint"
FRAME_COUNT = 81
LATENT_PHASES = 21
NUM_INFERENCE_STEPS = 40
FPS = 25
ULYSSES_SIZE = 4
SCHEDULE_SHA256 = (
    "46f3dcb6e2d65cb7921e5217e2a20dfe008b366cfacafe455fee4d3c45f63ae2"
)
BERNINI_OFFICIAL_COMMIT = "2d2b4591ac053ec25c6371b01a5a6746679e5793"
VEOMNI_TESTED_COMMIT = "f90b3dc6fbb0ce693745223cc7a94064123dbf4d"
CHECKPOINT_TREE_SHA256 = (
    "6be0d0db0dd483daf1a843efa2b5aafc20090ad11dc0fc6ee8859bdf150635ca"
)
EVENT_PHASE_ORDER = (
    "lower_hips_and_sit",
    "turn_head_to_registered_target",
    "stable_seated_hold",
)

_SHA1 = re.compile(r"[0-9a-f]{40}")
_SHA256 = re.compile(r"[0-9a-f]{64}")


class CaperNativeKSeedPopulationError(RuntimeError):
    """Raised before an incomplete, filtered, or prematurely opened population ships."""


def _object_sha256(value: Any) -> str:
    payload = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _plain_json(value: str | Path, *, label: str) -> tuple[Path, Mapping[str, Any]]:
    requested = Path(value).expanduser()
    if not requested.is_absolute() or requested.is_symlink():
        raise CaperNativeKSeedPopulationError(f"{label} path differs")
    path = requested.resolve(strict=True)
    if path != requested or not path.is_file() or path.is_symlink():
        raise CaperNativeKSeedPopulationError(f"{label} must be a plain absolute file")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception as error:
        raise CaperNativeKSeedPopulationError(f"{label} is not valid JSON") from error
    if not isinstance(payload, Mapping):
        raise CaperNativeKSeedPopulationError(f"{label} root differs")
    return path, payload


def _load_base() -> Any:
    # Keep registry/lockbox contract tests dependency-light.  The heavy frozen
    # Bernini native implementation is imported only by an actual render.
    import infer_t2v_v2v_branch_homotopy_canary as implementation

    return implementation


def _canonical_registry() -> Mapping[str, Any]:
    path = METHOD_ROOT / CANONICAL_REGISTRY_RELATIVE
    if (
        not path.is_file()
        or path.is_symlink()
        or _file_sha256(path) != CANONICAL_REGISTRY_SHA256
    ):
        raise CaperNativeKSeedPopulationError("sealed K-seed registry bytes differ")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except Exception as error:
        raise CaperNativeKSeedPopulationError(
            "sealed K-seed registry JSON differs"
        ) from error
    if not isinstance(value, Mapping):
        raise CaperNativeKSeedPopulationError("registry root differs")
    return value


def _validate_action_taxonomy(registry: Mapping[str, Any]) -> None:
    taxonomy = registry.get("action_taxonomy")
    if not isinstance(taxonomy, Mapping):
        raise CaperNativeKSeedPopulationError("action taxonomy differs")
    unsigned = dict(taxonomy)
    declared = unsigned.pop("action_taxonomy_sha256", None)
    intervals = unsigned.get("event_frame_intervals_inclusive")
    if (
        taxonomy.get("action_family_id") != ACTION_FAMILY_ID
        or taxonomy.get("event_phase_order") != list(EVENT_PHASE_ORDER)
        or intervals
        != {
            "lower_hips_and_sit": [0, 20],
            "turn_head_to_registered_target": [20, 40],
            "stable_seated_hold": [40, 80],
        }
        or taxonomy.get("phase_boundary_overlap_is_intentional") is not True
        or declared != ACTION_TAXONOMY_SHA256
        or _object_sha256(unsigned) != declared
    ):
        raise CaperNativeKSeedPopulationError("action taxonomy seal differs")


def _validate_native_contract(registry: Mapping[str, Any]) -> None:
    contract = registry.get("native_v2v_contract")
    if (
        not isinstance(contract, Mapping)
        or contract.get("arm") != NATIVE_ARM
        or contract.get("guidance_mode") != "v2v_apg"
        or contract.get("positive_task") != "mv2v"
        or contract.get("external_inference_inputs")
        != ["source_video", "target_action_caption"]
        or contract.get("full_source_video_count") != 1
        or any(
            contract.get(key) != 0
            for key in (
                "source_reference_count",
                "first_frame_anchor_count",
                "target_video_count",
                "mask_count",
                "track_count",
                "pose_count",
                "flow_count",
                "trajectory_count",
            )
        )
        or contract.get("custom_initial_noise") is not False
        or contract.get("official_gaussian_is_sampler_initial_noise") is not True
        or contract.get("official_gaussian_captured_by_read_only_observer") is not True
        or contract.get("observer_injects_or_replaces_noise") is not False
        or contract.get("frame_count") != FRAME_COUNT
        or contract.get("fps") != FPS
        or contract.get("latent_phases") != LATENT_PHASES
        or contract.get("num_inference_steps") != NUM_INFERENCE_STEPS
        or contract.get("flow_shift_from_renderer_config") != 5.0
        or contract.get("omega_text") != 4.0
        or contract.get("eta") != 0.5
        or contract.get("norm_threshold") != 50.0
        or contract.get("momentum") != 0.0
        or contract.get("exact40_shift5_schedule_sha256") != SCHEDULE_SHA256
        or contract.get("frozen_model") is not True
        or contract.get("training") is not False
        or contract.get("optimizer") is not False
        or contract.get("parameter_update") is not False
    ):
        raise CaperNativeKSeedPopulationError("native full-source V2V contract differs")


def _expected_cell_order(
    source_ids: Sequence[str], seeds: Sequence[int], *, phase: str
) -> list[str]:
    return [
        f"{phase}-{source_id}-s{seed}"
        for source_id in source_ids
        for seed in seeds
    ]


def _validate_population_design(registry: Mapping[str, Any]) -> None:
    population = registry.get("population_design")
    if (
        not isinstance(population, Mapping)
        or population.get("phase_order") != ["fit", "lockbox"]
        or population.get("default_launcher_phase") != "fit"
        or population.get(
            "fit_and_lockbox_never_aggregated_as_independent_training_targets"
        )
        is not True
        or population.get("all_registered_cells_must_materialize_before_phase_receipt")
        is not True
        or population.get("partial_population_scientific_claim_authorized") is not False
        or population.get("posthoc_seed_selection_authorized") is not False
    ):
        raise CaperNativeKSeedPopulationError("population root differs")
    for phase in ("fit", "lockbox"):
        row = population.get(phase)
        expected_sources = list(PHASE_SOURCE_IDS[phase])
        expected_seeds = list(PHASE_SEEDS[phase])
        expected_cells = list(PHASE_CELL_ORDER[phase])
        if (
            not isinstance(row, Mapping)
            or row.get("source_ids") != expected_sources
            or row.get("seeds") != expected_seeds
            or row.get("cell_order") != expected_cells
            or row.get("cell_order")
            != _expected_cell_order(expected_sources, expected_seeds, phase=phase)
            or row.get("cartesian_population_required") is not True
            or row.get("expected_cell_count") != len(expected_cells)
            or row.get("seed_filtering_or_best_of_k_authorized") is not False
        ):
            raise CaperNativeKSeedPopulationError(f"{phase} Cartesian population differs")
    lockbox = population["lockbox"]
    if (
        lockbox.get("explicit_second_stage_switch_required") is not True
        or lockbox.get("threshold_freeze_receipt_required") is not True
        or lockbox.get("lockbox_media_must_remain_unopened_before_freeze") is not True
    ):
        raise CaperNativeKSeedPopulationError("lockbox release boundary differs")


def _validate_sources(registry: Mapping[str, Any]) -> Mapping[str, Mapping[str, Any]]:
    rows = registry.get("sources")
    if not isinstance(rows, list) or len(rows) != 6:
        raise CaperNativeKSeedPopulationError("source registry differs")
    by_id: dict[str, Mapping[str, Any]] = {}
    for row in rows:
        if not isinstance(row, Mapping):
            raise CaperNativeKSeedPopulationError("source row differs")
        source_id = row.get("source_id")
        if not isinstance(source_id, str) or source_id in by_id:
            raise CaperNativeKSeedPopulationError("source ID differs")
        split = row.get("split")
        expected_split = (
            "fit" if source_id in FIT_SOURCE_IDS else "lockbox"
            if source_id in LOCKBOX_SOURCE_IDS
            else None
        )
        source_hw = row.get("source_hw")
        bucket_hw = row.get("bucket_hw")
        latent_shape = row.get("latent_shape")
        if (
            split != expected_split
            or not isinstance(row.get("identity_id"), str)
            or not isinstance(row.get("scene_id"), str)
            or row.get("registered_turn_target") not in {
                "frame_right",
                "frame_right_toward_background",
                "camera",
            }
            or not isinstance(row.get("source_video"), str)
            or not str(row["source_video"]).endswith(
                f"/samples/{source_id}/samples/{source_id}/source_video.mp4"
            )
            or _SHA256.fullmatch(str(row.get("source_video_sha256"))) is None
            or not isinstance(source_hw, list)
            or len(source_hw) != 2
            or not all(type(value) is int and value > 0 for value in source_hw)
            or not isinstance(bucket_hw, list)
            or len(bucket_hw) != 2
            or not all(type(value) is int and value % 16 == 0 for value in bucket_hw)
            or latent_shape
            != [1, 16, LATENT_PHASES, bucket_hw[0] // 8, bucket_hw[1] // 8]
            or _sha256_text(str(row.get("target_action_caption")))
            != row.get("target_action_caption_sha256")
        ):
            raise CaperNativeKSeedPopulationError(f"source {source_id!r} differs")
        caption = str(row["target_action_caption"])
        for phrase in (
            "From frames 0 through 20",
            "From frames 20 through 40",
            "From frames 40 through 80",
            "Preserve the source",
        ):
            if phrase not in caption:
                raise CaperNativeKSeedPopulationError(
                    f"source {source_id!r} phase caption differs"
                )
        by_id[source_id] = row
    if tuple(source_id for source_id in FIT_SOURCE_IDS if source_id in by_id) != FIT_SOURCE_IDS:
        raise CaperNativeKSeedPopulationError("fit source closure differs")
    if tuple(source_id for source_id in LOCKBOX_SOURCE_IDS if source_id in by_id) != LOCKBOX_SOURCE_IDS:
        raise CaperNativeKSeedPopulationError("lockbox source closure differs")
    return by_id


def _validate_posthoc_negative(registry: Mapping[str, Any]) -> None:
    row = registry.get("posthoc_negative_control")
    if (
        not isinstance(row, Mapping)
        or row.get("source_id") != "a66e6818e4144928"
        or row.get("source_video_sha256")
        != "0fdc54d89250f355d2170a4d6f6aac0867abf592afb849668a8e2879a6617147"
        or row.get("negative_action_family_id") != "human-stand-up-and-hold"
        or row.get("role") != "posthoc_wrong_family_audit_only"
        or row.get("generation_by_this_launcher_authorized") is not False
        or row.get("optimizer_materialization_authorized") is not False
        or row.get("threshold_selection_authorized") is not False
        or row.get("bucket_hw") != [544, 432]
        or row.get("latent_shape") != [1, 16, 21, 68, 54]
    ):
        raise CaperNativeKSeedPopulationError("a66e post-hoc negative differs")


def _validate_registry(registry: Mapping[str, Any]) -> Mapping[str, Mapping[str, Any]]:
    canonical = _canonical_registry()
    if registry != canonical:
        raise CaperNativeKSeedPopulationError("registry differs from sealed authority")
    if (
        registry.get("schema_version") != REGISTRY_SCHEMA_VERSION
        or registry.get("method") != METHOD
    ):
        raise CaperNativeKSeedPopulationError("registry root differs")
    _validate_action_taxonomy(registry)
    _validate_native_contract(registry)
    _validate_population_design(registry)
    sources = _validate_sources(registry)
    _validate_posthoc_negative(registry)
    release = registry.get("lockbox_release_contract")
    if (
        not isinstance(release, Mapping)
        or release.get("schema_version") != THRESHOLD_FREEZE_SCHEMA_VERSION
        or release.get("fit_population_cell_ids_sha256") != FIT_CELL_IDS_SHA256
        or release.get("receipt_digest_required") is not True
    ):
        raise CaperNativeKSeedPopulationError("threshold-freeze contract differs")
    return sources


def _registry_cell(
    registry: Mapping[str, Any], *, cell_id: str, population_phase: str
) -> Mapping[str, Any]:
    sources = _validate_registry(registry)
    if population_phase not in PHASE_CELL_ORDER:
        raise CaperNativeKSeedPopulationError("population phase differs")
    if cell_id not in PHASE_CELL_ORDER[population_phase]:
        raise CaperNativeKSeedPopulationError("cell is outside the requested phase")
    for source_id in PHASE_SOURCE_IDS[population_phase]:
        for seed in PHASE_SEEDS[population_phase]:
            expected = f"{population_phase}-{source_id}-s{seed}"
            if expected == cell_id:
                return {
                    **dict(sources[source_id]),
                    "cell_id": cell_id,
                    "population_phase": population_phase,
                    "seed": seed,
                    "action_family_id": ACTION_FAMILY_ID,
                    "action_taxonomy_sha256": ACTION_TAXONOMY_SHA256,
                    "selected_before_generation": True,
                    "seed_filtering_or_best_of_k_authorized": False,
                }
    raise CaperNativeKSeedPopulationError("cell Cartesian coordinates differ")


def _validate_threshold_freeze_receipt(
    value: str | Path,
    *,
    expected_sha256: str,
    runtime_source_revision: str,
) -> Mapping[str, Any]:
    try:
        path, payload = _plain_json(value, label="threshold-freeze receipt")
    except Exception as error:
        raise CaperNativeKSeedPopulationError(str(error)) from error
    if (
        _SHA256.fullmatch(expected_sha256) is None
        or _file_sha256(path) != expected_sha256
    ):
        raise CaperNativeKSeedPopulationError("threshold-freeze file hash differs")
    required_fields = {
        "schema_version",
        "registry_sha256",
        "action_family_id",
        "action_taxonomy_sha256",
        "runtime_source_revision",
        "fit_population_complete",
        "fit_population_receipt_sha256",
        "fit_population_cell_ids_sha256",
        "reward_thresholds_sha256",
        "evaluation_protocol_sha256",
        "method_and_thresholds_frozen_before_lockbox",
        "lockbox_media_opened_before_freeze_is_false",
        "lockbox_generation_authorized",
        "receipt_digest",
    }
    if set(payload) != required_fields:
        raise CaperNativeKSeedPopulationError("threshold-freeze fields differ")
    unsigned = dict(payload)
    declared = unsigned.pop("receipt_digest", None)
    for key in (
        "registry_sha256",
        "action_taxonomy_sha256",
        "fit_population_receipt_sha256",
        "fit_population_cell_ids_sha256",
        "reward_thresholds_sha256",
        "evaluation_protocol_sha256",
        "receipt_digest",
    ):
        if _SHA256.fullmatch(str(payload.get(key))) is None:
            raise CaperNativeKSeedPopulationError(
                f"threshold-freeze {key} differs"
            )
    if (
        payload.get("schema_version") != THRESHOLD_FREEZE_SCHEMA_VERSION
        or payload.get("registry_sha256") != CANONICAL_REGISTRY_SHA256
        or payload.get("action_family_id") != ACTION_FAMILY_ID
        or payload.get("action_taxonomy_sha256") != ACTION_TAXONOMY_SHA256
        or payload.get("runtime_source_revision") != runtime_source_revision
        or payload.get("fit_population_complete") is not True
        or payload.get("fit_population_cell_ids_sha256") != FIT_CELL_IDS_SHA256
        or payload.get("method_and_thresholds_frozen_before_lockbox") is not True
        or payload.get("lockbox_media_opened_before_freeze_is_false") is not True
        or payload.get("lockbox_generation_authorized") is not True
        or _object_sha256(unsigned) != declared
    ):
        raise CaperNativeKSeedPopulationError("threshold-freeze seal differs")
    return {
        "path": str(path),
        "artifact_sha256": expected_sha256,
        "receipt_digest": declared,
        "fit_population_receipt_sha256": payload["fit_population_receipt_sha256"],
        "fit_population_cell_ids_sha256": payload["fit_population_cell_ids_sha256"],
        "reward_thresholds_sha256": payload["reward_thresholds_sha256"],
        "evaluation_protocol_sha256": payload["evaluation_protocol_sha256"],
        "runtime_source_revision": payload["runtime_source_revision"],
        "method_and_thresholds_frozen_before_lockbox": True,
        "lockbox_media_opened_before_freeze_is_false": True,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", required=True)
    parser.add_argument("--expected-registry-sha256", required=True)
    parser.add_argument("--population-phase", choices=("fit", "lockbox"), required=True)
    parser.add_argument("--cell-id", choices=CELL_ORDER, required=True)
    parser.add_argument("--lockbox-second-stage-enabled", action="store_true")
    parser.add_argument("--threshold-freeze-receipt")
    parser.add_argument("--expected-threshold-freeze-sha256")
    parser.add_argument("--bernini-root", required=True)
    parser.add_argument("--veomni-root", required=True)
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--checkpoint-content-manifest", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--runtime-source-revision", required=True)
    parser.add_argument("--runtime-source-archive-sha256", required=True)
    parser.add_argument("--runtime-source-closure-sha256", required=True)
    parser.add_argument("--launcher-source-sha256", required=True)
    parser.add_argument(
        "--expected-bernini-commit",
        default=BERNINI_OFFICIAL_COMMIT,
    )
    parser.add_argument(
        "--expected-veomni-commit",
        default=VEOMNI_TESTED_COMMIT,
    )
    parser.add_argument(
        "--expected-checkpoint-tree-sha256",
        default=CHECKPOINT_TREE_SHA256,
    )
    return parser


def _validate_cli(args: argparse.Namespace) -> None:
    for name in (
        "expected_registry_sha256",
        "runtime_source_archive_sha256",
        "runtime_source_closure_sha256",
        "launcher_source_sha256",
        "expected_checkpoint_tree_sha256",
    ):
        if _SHA256.fullmatch(str(getattr(args, name))) is None:
            raise CaperNativeKSeedPopulationError(f"{name} differs")
    for name in (
        "runtime_source_revision",
        "expected_bernini_commit",
        "expected_veomni_commit",
    ):
        if _SHA1.fullmatch(str(getattr(args, name))) is None:
            raise CaperNativeKSeedPopulationError(f"{name} differs")
    if args.expected_registry_sha256 != CANONICAL_REGISTRY_SHA256:
        raise CaperNativeKSeedPopulationError("canonical registry digest differs")
    if args.expected_bernini_commit != BERNINI_OFFICIAL_COMMIT:
        raise CaperNativeKSeedPopulationError("Bernini revision differs")
    if args.expected_veomni_commit != VEOMNI_TESTED_COMMIT:
        raise CaperNativeKSeedPopulationError("VeOmni revision differs")
    if (
        args.expected_checkpoint_tree_sha256
        != CHECKPOINT_TREE_SHA256
    ):
        raise CaperNativeKSeedPopulationError("checkpoint tree differs")
    if args.population_phase == "fit":
        if (
            args.lockbox_second_stage_enabled
            or args.threshold_freeze_receipt is not None
            or args.expected_threshold_freeze_sha256 is not None
        ):
            raise CaperNativeKSeedPopulationError(
                "fit phase cannot consume lockbox release authority"
            )
    elif (
        not args.lockbox_second_stage_enabled
        or args.threshold_freeze_receipt is None
        or args.expected_threshold_freeze_sha256 is None
    ):
        raise CaperNativeKSeedPopulationError(
            "lockbox requires explicit second-stage switch and threshold freeze"
        )
    if args.cell_id not in PHASE_CELL_ORDER[args.population_phase]:
        raise CaperNativeKSeedPopulationError("CLI phase/cell mismatch")


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    _validate_cli(args)
    try:
        registry_path, registry = _plain_json(args.registry, label="registry")
    except Exception as error:
        raise CaperNativeKSeedPopulationError(str(error)) from error
    if _file_sha256(registry_path) != args.expected_registry_sha256:
        raise CaperNativeKSeedPopulationError("registry file digest differs")
    cell = _registry_cell(
        registry, cell_id=args.cell_id, population_phase=args.population_phase
    )
    threshold_freeze = None
    if args.population_phase == "lockbox":
        threshold_freeze = _validate_threshold_freeze_receipt(
            args.threshold_freeze_receipt,
            expected_sha256=args.expected_threshold_freeze_sha256,
            runtime_source_revision=args.runtime_source_revision,
        )
    base = _load_base()
    output_dir = base.native._resolve_fresh_output_dir(args.output_dir)

    source_requested = Path(str(cell["source_video"])).expanduser()
    if not source_requested.is_absolute() or source_requested.is_symlink():
        raise CaperNativeKSeedPopulationError("source path differs")
    source_path = source_requested.resolve(strict=True)
    if (
        source_path != source_requested
        or not source_path.is_file()
        or base.native.legacy.file_sha256(source_path) != cell["source_video_sha256"]
    ):
        raise CaperNativeKSeedPopulationError("source bytes differ")

    try:
        bernini_root, veomni_root, bernini_revision, veomni_revision = (
            base.native.legacy.trainer.validate_source_trees(
                args.bernini_root,
                args.veomni_root,
                expected_bernini_commit=args.expected_bernini_commit,
                expected_veomni_commit=args.expected_veomni_commit,
            )
        )
        checkpoint, transformer_config = base.native.legacy.trainer.validate_checkpoint(
            args.checkpoint
        )
    except Exception as error:
        raise CaperNativeKSeedPopulationError(str(error)) from error
    if int(transformer_config["num_attention_heads"]) % ULYSSES_SIZE:
        raise CaperNativeKSeedPopulationError("attention heads do not divide Ulysses4")
    inference_file_hashes = base.native.legacy.validate_inference_source_files(
        bernini_root
    )
    base.native.legacy.trainer.activate_source_trees(bernini_root, veomni_root)

    import torch
    import torch.distributed as dist
    from diffusers import __version__ as diffusers_version
    from diffusers.models import AutoencoderKLWan
    from diffusers.pipelines.wan.pipeline_wan import prompt_clean
    from transformers import AutoTokenizer, __version__ as transformers_version
    from bernini.cli import DEFAULT_NEG_PROMPT
    from bernini.io_utils import save_output
    import bernini.models.wan_diffusion as wan_diffusion
    from bernini.models.renderer import BerniniRendererConfig, BerniniRendererModel
    from bernini.parallel import init_parallel_state
    from bernini.pipeline import _vae_encode
    from bernini.training.data import SYSTEM_PROMPTS

    if SYSTEM_PROMPTS.get("mv2v") != base.native.legacy.MV2V_SYSTEM_PROMPT:
        raise CaperNativeKSeedPopulationError("runtime MV2V system prompt differs")
    if DEFAULT_NEG_PROMPT != base.native.legacy.DEFAULT_NEGATIVE_PROMPT:
        raise CaperNativeKSeedPopulationError("runtime negative prompt differs")

    distributed = base.native.legacy.inference_distributed_contract()
    if (
        distributed.world_size != ULYSSES_SIZE
        or distributed.ulysses_size != ULYSSES_SIZE
        or not torch.cuda.is_available()
        or getattr(torch.version, "hip", None) is None
    ):
        raise CaperNativeKSeedPopulationError("runtime requires AUH WORLD4/SP4 ROCm")
    torch.cuda.set_device(distributed.local_rank)
    dist.init_process_group(
        backend="nccl",
        timeout=timedelta(minutes=240),
        rank=distributed.rank,
        world_size=distributed.world_size,
    )
    init_parallel_state(ulysses_size=ULYSSES_SIZE)
    device = torch.device("cuda", distributed.local_rank)

    checkpoint_rows: list[Any] = [None]
    checkpoint_manifest = Path(args.checkpoint_content_manifest).expanduser()
    if distributed.rank == 0:
        try:
            checkpoint_rows[0] = {
                "ok": True,
                "identity": base.source_audit.validate_checkpoint_content(
                    checkpoint, checkpoint_manifest
                ),
            }
        except Exception as error:
            checkpoint_rows[0] = {"ok": False, "error": str(error)}
    dist.broadcast_object_list(checkpoint_rows, src=0)
    if (
        not isinstance(checkpoint_rows[0], Mapping)
        or checkpoint_rows[0].get("ok") is not True
    ):
        raise CaperNativeKSeedPopulationError(
            f"checkpoint validation failed: {checkpoint_rows[0]}"
        )
    checkpoint_identity = dict(checkpoint_rows[0]["identity"])

    source_tensor, source_metadata, source_sha = (
        base.source_audit.prepare_hashed_source_snapshot(source_path)
    )
    bucket_hw = tuple(int(item) for item in cell["bucket_hw"])
    latent_shape = tuple(int(item) for item in cell["latent_shape"])
    if (
        source_sha != cell["source_video_sha256"]
        or source_metadata.get("frame_count") != FRAME_COUNT
        or abs(float(source_metadata.get("reported_fps", 0.0)) - FPS) > 1.0e-6
        or tuple(source_metadata.get("source_input_hw", ()))
        != tuple(cell["source_hw"])
        or tuple(source_metadata.get("source_derived_bucket_hw", ())) != bucket_hw
    ):
        raise CaperNativeKSeedPopulationError("source exact81 geometry differs")

    caption = str(cell["target_action_caption"])
    positive_prompt = base.build_mode_native_prompt(
        "source-mv2v", caption, prompt_cleaner=prompt_clean
    )
    tokenizer = AutoTokenizer.from_pretrained(
        str(checkpoint),
        subfolder="tokenizer",
        **base.native.legacy.tokenizer_load_kwargs(),
    )
    positive_ids, positive_mask = base.native.legacy._tokenize_training_prompt(
        tokenizer, positive_prompt
    )
    negative_ids, negative_mask = base.native.legacy._tokenize_renderer_negative(
        tokenizer, base.native.legacy.DEFAULT_NEGATIVE_PROMPT
    )

    config = BerniniRendererConfig.from_pretrained(
        str(bernini_root / "configs/bernini_renderer_wan21_1p3b"),
        local_files_only=True,
        **base.native.legacy.inference_renderer_config_overrides(checkpoint),
    )
    config.dtype = torch.bfloat16
    base.native.legacy.trainer.validate_renderer_config_mapping(
        config.to_dict(), checkpoint
    )
    if float(config.shift) != 5.0 or config.use_unipc is not True:
        raise CaperNativeKSeedPopulationError("renderer exact40 shift5 UniPC differs")
    model = BerniniRendererModel(config)
    model.eval().requires_grad_(False)
    freeze_before = base._strong_model_freeze_certificate(model)

    vae = AutoencoderKLWan.from_pretrained(
        str(checkpoint),
        subfolder="vae",
        torch_dtype=torch.float32,
        local_files_only=True,
    )
    vae.eval().requires_grad_(False)
    vae.to(device)
    if distributed.rank == 0:
        source_pixels = source_tensor.to(device=device, dtype=torch.float32)
        with torch.inference_mode():
            source_latent = _vae_encode(vae, source_pixels).contiguous()
        del source_pixels
    else:
        source_latent = torch.empty(latent_shape, device=device, dtype=torch.float32)
    dist.broadcast(source_latent, src=0)
    if tuple(source_latent.shape) != latent_shape:
        raise CaperNativeKSeedPopulationError("full source latent geometry differs")
    condition_identity = base.native._all_rank_tensor_identity(
        source_latent,
        label=f"{args.cell_id}_full_source_video",
        world_size=ULYSSES_SIZE,
    )
    vae.to("cpu")
    del source_tensor
    torch.cuda.empty_cache()

    model.to(device)
    model.t5_text_encoder.to(device)
    with torch.inference_mode():
        positive_embeds = model.encode_prompt(
            positive_ids.to(device), positive_mask.to(device)
        ).detach()
        uncond_embeds = model.encode_prompt(
            negative_ids.to(device), negative_mask.to(device)
        ).detach()
    expected_embed_shape = (1, 512, 4096)
    if any(
        tuple(value.shape) != expected_embed_shape
        for value in (positive_embeds, uncond_embeds)
    ):
        raise CaperNativeKSeedPopulationError("MV2V embedding geometry differs")
    model.t5_text_encoder.to("cpu")
    torch.cuda.empty_cache()

    diffusion = base.sampler_contract.resolve_diffusion_core(model.diff_dec)
    wan_source_sha = base.sampler_contract.validate_runtime_source_identity(
        bernini_commit=bernini_revision,
        wan_diffusion_path=Path(wan_diffusion.__file__).resolve(),
    )
    base.sampler_contract._validate_scheduler_contract(
        diffusion.scheduler, expected_flow_shift=5.0
    )
    if diffusion.transformer_2 is not None:
        raise CaperNativeKSeedPopulationError(
            "population requires Bernini-R 1.3B single DiT"
        )
    schedule_receipt = base.branch_base.pinned_exact40_schedule_receipt()
    if schedule_receipt.get("digest") != SCHEDULE_SHA256:
        raise CaperNativeKSeedPopulationError("pinned exact40 schedule differs")

    sample_kwargs = {
        "prompt_embeds": positive_embeds,
        "uncond_prompt_embeds": uncond_embeds,
        **base.conditions_for_arm(NATIVE_ARM, source_latent=source_latent),
        "width": bucket_hw[1],
        "height": bucket_hw[0],
        "device": device,
        **base.sampling_contract(NATIVE_ARM, seed=int(cell["seed"])),
    }
    with torch.inference_mode():
        result, capture = base.native._sample_with_native_initial_noise_observer(
            sample_fn=lambda: diffusion.sample(**sample_kwargs),
            wan_diffusion_module=wan_diffusion,
            expected_shape=latent_shape,
            expected_device=device,
            expected_seed=int(cell["seed"]),
        )
    if (
        not isinstance(result, torch.Tensor)
        or tuple(result.shape) != latent_shape
        or result.dtype != torch.float32
        or result.requires_grad
        or result.grad_fn is not None
        or not bool(torch.isfinite(result).all().item())
    ):
        raise CaperNativeKSeedPopulationError("native sampler result differs")
    stored = result.detach().to(device="cpu").contiguous()
    generated_identity = base.native._all_rank_tensor_identity(
        stored, label=f"{args.cell_id}_{NATIVE_ARM}", world_size=ULYSSES_SIZE
    )
    noise_identity = base.native._all_rank_tensor_identity(
        capture.tensor,
        label=f"{args.cell_id}_{NATIVE_ARM}_official_initial_gaussian",
        world_size=ULYSSES_SIZE,
    )
    runtime_trace = {
        "native_endpoint": True,
        "guidance_mode": "v2v_apg",
        "positive_task": "mv2v",
        "expected_transformer_forwards_per_step_from_pinned_vendor": 2,
        "runtime_hook_installed": False,
        "vendor_source_sha256": wan_source_sha,
        "source_video_count": 1,
        "source_reference_count": 0,
        "target_video_count": 0,
        "mask_track_pose_flow_count": 0,
        "num_inference_steps": NUM_INFERENCE_STEPS,
        "schedule_sha256": SCHEDULE_SHA256,
    }
    trace_digest = _object_sha256(runtime_trace)
    trace_rows: list[Any] = [None] * ULYSSES_SIZE
    dist.all_gather_object(trace_rows, trace_digest)
    if len(set(trace_rows)) != 1:
        raise CaperNativeKSeedPopulationError("native trace differs across SP4 ranks")

    freeze_after = base._strong_model_freeze_certificate(model)
    if freeze_after != freeze_before or any(p.requires_grad for p in model.parameters()):
        raise CaperNativeKSeedPopulationError("frozen model changed")
    model.to("cpu")
    torch.cuda.empty_cache()

    after_rows: list[Any] = [None]
    if distributed.rank == 0:
        try:
            after_rows[0] = {
                "ok": True,
                "identity": base.source_audit.validate_checkpoint_content(
                    checkpoint, checkpoint_manifest
                ),
            }
        except Exception as error:
            after_rows[0] = {"ok": False, "error": str(error)}
    dist.broadcast_object_list(after_rows, src=0)
    if (
        not isinstance(after_rows[0], Mapping)
        or after_rows[0].get("identity") != checkpoint_identity
    ):
        raise CaperNativeKSeedPopulationError("checkpoint content changed")

    if distributed.rank == 0:
        output_dir.mkdir(parents=False, exist_ok=False)
        noise_artifact = base.native._save_initial_noise_atomically(
            output_dir / f"{NATIVE_ARM}.official-initial-gaussian.safetensors",
            capture,
            all_rank_identity=noise_identity,
        )
        generated_for_decode = {NATIVE_ARM: stored.to(device=device).contiguous()}
        try:
            outputs = base.native._save_outputs(
                output_dir=output_dir,
                generated=generated_for_decode,
                vae=vae,
                bucket_hw=bucket_hw,
                device=device,
                save_output_fn=save_output,
            )
        finally:
            generated_for_decode.clear()
        receipt: dict[str, Any] = {
            "schema_version": SCHEMA_VERSION,
            "method": METHOD,
            "cell_id": args.cell_id,
            "population_phase": args.population_phase,
            "registry": {
                "path": str(registry_path),
                "sha256": CANONICAL_REGISTRY_SHA256,
                "action_family_id": ACTION_FAMILY_ID,
                "action_taxonomy_sha256": ACTION_TAXONOMY_SHA256,
                "complete_phase_cell_order": list(
                    PHASE_CELL_ORDER[args.population_phase]
                ),
                "complete_phase_population_required": True,
                "seed_filtering_or_best_of_k_authorized": False,
            },
            "input": {
                "accepted_external_conditions": [
                    "source_video",
                    "target_action_caption",
                ],
                "source_id": cell["source_id"],
                "identity_id": cell["identity_id"],
                "scene_id": cell["scene_id"],
                "actor_kind": cell["actor_kind"],
                "source_video": str(source_path),
                "source_video_sha256": source_sha,
                "target_action_caption": caption,
                "target_action_caption_sha256": _sha256_text(caption),
                "registered_turn_target": cell["registered_turn_target"],
                "event_phase_order": list(EVENT_PHASE_ORDER),
                "target_video": False,
                "custom_initial_noise": False,
                "generated_owner_media": False,
                "mask": False,
                "track": False,
                "pose": False,
                "flow": False,
                "trajectory": False,
                "first_frame_anchor": False,
                "source_reference": False,
            },
            "preprocessing": dict(source_metadata),
            "prompt": {
                "positive_task": "mv2v",
                "full_prompt_sha256": _sha256_text(positive_prompt),
                "negative_prompt_sha256": _sha256_text(
                    base.native.legacy.DEFAULT_NEGATIVE_PROMPT
                ),
                "embedding_shape": list(expected_embed_shape),
            },
            "conditions": {
                "full_source_video_count": 1,
                "source_reference_count": 0,
                "first_frame_anchor_count": 0,
                "target_video_count": 0,
                "mask_track_pose_flow_trajectory_count": 0,
                "full_source_identity": condition_identity,
            },
            "sampling": {
                "arm": NATIVE_ARM,
                "guidance_mode": "v2v_apg",
                "frame_count": FRAME_COUNT,
                "latent_phases": LATENT_PHASES,
                "num_inference_steps": NUM_INFERENCE_STEPS,
                "fps": FPS,
                "seed": int(cell["seed"]),
                "official_gaussian_raw_sha256": capture.raw_value_sha256,
                "official_gaussian_is_sampler_initial_noise": True,
                "official_gaussian_captured_by_read_only_observer": True,
                "observer_injects_or_replaces_noise": False,
                "external_initial_noise_injection": False,
                "target_patch_tokens": LATENT_PHASES
                * (bucket_hw[0] // 16)
                * (bucket_hw[1] // 16),
                "flow_shift_from_renderer_config": float(config.shift),
                "omega_text": 4.0,
                "eta": 0.5,
                "norm_threshold": 50.0,
                "momentum": 0.0,
                "schedule_sha256": SCHEDULE_SHA256,
                "schedule_receipt": schedule_receipt,
                "native_target_initialization": base.native.TARGET_INITIALIZATION,
            },
            "runtime_trace": runtime_trace,
            "runtime_trace_digest": trace_digest,
            "generated_identity": generated_identity,
            "official_initial_gaussian": noise_artifact,
            "outputs": outputs,
            "threshold_freeze": threshold_freeze,
            "checkpoint": checkpoint_identity,
            "freeze_certificate": freeze_after,
            "source_revisions": {
                "bernini": bernini_revision,
                "veomni": veomni_revision,
                "wan_diffusion_sha256": wan_source_sha,
                "runtime_method": args.runtime_source_revision,
                "runtime_source_archive_sha256": args.runtime_source_archive_sha256,
                "runtime_source_closure_sha256": args.runtime_source_closure_sha256,
                "launcher_source_sha256": args.launcher_source_sha256,
                "inference_files": inference_file_hashes,
            },
            "runtime_versions": {
                "torch": torch.__version__,
                "torch_hip": str(torch.version.hip),
                "diffusers": diffusers_version,
                "transformers": transformers_version,
            },
            "training_performed": False,
            "optimizer_created": False,
            "parameter_update": False,
            "all_registered_cells_required_before_phase_claim": True,
            "seed_filtering_or_best_of_k_authorized": False,
            "partial_population_scientific_claim_authorized": False,
            "scientific_or_action_editing_claim_authorized": False,
            "a66e_generated_by_this_runner": False,
        }
        receipt["receipt_digest"] = _object_sha256(receipt)
        base.value_audit.write_receipt_atomically(
            output_dir / "receipt.json", receipt
        )
        print(base.native.legacy.canonical_json_bytes(receipt).decode("ascii"), flush=True)

    dist.barrier()
    del source_latent, stored, capture
    dist.destroy_process_group()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "ACTION_FAMILY_ID",
    "ACTION_TAXONOMY_SHA256",
    "CANONICAL_REGISTRY_RELATIVE",
    "CANONICAL_REGISTRY_SHA256",
    "CELL_ORDER",
    "CaperNativeKSeedPopulationError",
    "FIT_CELL_ORDER",
    "FIT_SEEDS",
    "FIT_SOURCE_IDS",
    "LOCKBOX_CELL_ORDER",
    "LOCKBOX_SEEDS",
    "LOCKBOX_SOURCE_IDS",
    "METHOD",
    "NATIVE_ARM",
    "SCHEMA_VERSION",
    "THRESHOLD_FREEZE_SCHEMA_VERSION",
    "_registry_cell",
    "_validate_threshold_freeze_receipt",
    "build_parser",
    "main",
]
