#!/usr/bin/env python3
"""Phase-routed Stage-B action operator for frozen Bernini-R 1.3B.

This replaces the exploratory discrete typed-arrow router with an online
representation generated by :mod:`saic_online_motion_field_v1`.  For each
target-row hidden state in blocks 0..22 cross-attention Q/O, the native target
token's exact81 latent phase selects one of the 21 frozen 32-D motion codes::

    delta(h_i) = up(silu(state_down(h_i)) * tanh(phase_gate(code[phase(i)])))

All learned maps are bias-free FP32 rank 8 and ``up`` is zero initialized.
Thus installation is byte-exact and the only trainable parameters are the
registered ``attn2.to_q`` / ``attn2.to_out[0]`` maps.  Native source-video,
reference, and append-padding rows are never changed.  Exact40 indices 38/39
and exact-zero online no-op codes return the frozen projection directly,
without evaluating the learned path.

The route is minted from the already-built native V/VI branch, audited live
UniPC scheduler/timestep, Bernini's live Ulysses state, and the exact current
noisy target object used to build the online field.  Callers cannot report a
mask, rank, SP size, schedule index, sigma, phase map, action ID, or phase
code.  Training and inference therefore enter precisely the same route.
"""

from __future__ import annotations

from contextlib import contextmanager
from contextvars import ContextVar, Token
from dataclasses import dataclass, field
import hashlib
import json
import math
from typing import Any, Iterator, Mapping, Optional
import weakref

import torch
from torch import nn
from torch.nn import functional as F

if __package__:
    from . import inference_sigma_strata as sigma_strata
    from . import saic_online_motion_field_v1 as online_motion
    from . import source_self_native_ref_contrastive_v3 as native_pack
else:  # Direct import from methods/bernini_action_editing.
    import inference_sigma_strata as sigma_strata
    import saic_online_motion_field_v1 as online_motion
    import source_self_native_ref_contrastive_v3 as native_pack


SCHEMA_VERSION = "bernini-saic-temporal-action-operator-v2"
CLASSIFICATION = "stage_b_operator_primitive/no_training_authority"
TOTAL_BLOCKS_1P3B = 30
ACTION_BLOCK_INDICES = tuple(range(23))
ACTION_OPERATOR_RANK = 8
ACTIVE_SIGMA_INDICES = tuple(range(38))
LOW_SIGMA_EXACT_BASE_INDICES = (38, 39)
FULL_SOURCE_BRANCHES = ("V", "VI")
ALLOWED_SP_SIZES = frozenset({1, 4})

_ROUTE_MINT = object()


class SAICTemporalActionOperatorError(RuntimeError):
    """Raised before an ambiguous online action route can execute."""


def _canonical_json(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
            allow_nan=False,
        ).encode("ascii")
    except (TypeError, ValueError, UnicodeEncodeError) as error:
        raise SAICTemporalActionOperatorError(
            f"value is not canonical finite ASCII JSON: {error}"
        ) from error


def _object_sha256(value: Any) -> str:
    return hashlib.sha256(_canonical_json(value)).hexdigest()


def _storage_pointer(value: torch.Tensor) -> int:
    try:
        return int(value.untyped_storage().data_ptr())
    except AttributeError:  # pragma: no cover - older torch compatibility
        return int(value.storage().data_ptr())


def _tensor_binding(value: torch.Tensor) -> tuple[Any, ...]:
    return (
        id(value),
        _storage_pointer(value),
        int(value.storage_offset()),
        tuple(map(int, value.shape)),
        tuple(map(int, value.stride())),
        value.dtype,
        value.device,
        value.layout,
        int(getattr(value, "_version", 0)),
    )


def _assert_tensor_binding(
    value: Any, expected: tuple[Any, ...], *, label: str
) -> torch.Tensor:
    if type(value) is not torch.Tensor or _tensor_binding(value) != expected:
        raise SAICTemporalActionOperatorError(f"bound runtime {label} changed")
    return value


def _gradient_checkpointing_flags(transformer: nn.Module) -> tuple[str, ...]:
    owners: list[tuple[str, Any]] = [("transformer", transformer)]
    config = getattr(transformer, "config", None)
    if config is not None:
        owners.append(("transformer.config", config))
    owners.extend(
        (f"blocks.{index}", block)
        for index, block in enumerate(tuple(getattr(transformer, "blocks", ())))
    )
    enabled: list[str] = []
    for owner_name, owner in owners:
        for attribute in (
            "gradient_checkpointing",
            "is_gradient_checkpointing",
            "_gradient_checkpointing",
        ):
            value = (
                owner.get(attribute)
                if isinstance(owner, Mapping)
                else getattr(owner, attribute, None)
            )
            if callable(value) or value is None:
                continue
            try:
                active = bool(value)
            except Exception as error:
                raise SAICTemporalActionOperatorError(
                    f"cannot audit {owner_name}.{attribute}"
                ) from error
            if active:
                enabled.append(f"{owner_name}.{attribute}")
    return tuple(enabled)


def _assert_gradient_checkpointing_disabled(transformer: nn.Module) -> None:
    enabled = _gradient_checkpointing_flags(transformer)
    if enabled:
        raise SAICTemporalActionOperatorError(
            "gradient checkpointing is forbidden for online routed execution: "
            f"{enabled[:3]}"
        )


def _get_live_parallel_state() -> Any:
    """Return Bernini's actual parallel state; tests patch this private seam."""

    try:
        from bernini.parallel import get_parallel_state

        state = get_parallel_state()
    except Exception as error:
        raise SAICTemporalActionOperatorError(
            "Bernini live parallel state is unavailable"
        ) from error
    if state is None:
        raise SAICTemporalActionOperatorError(
            "Bernini live parallel state is unavailable"
        )
    return state


def _parallel_coordinates(state: Any) -> tuple[int, int]:
    rank = getattr(state, "ulysses_rank", None)
    size = getattr(state, "ulysses_size", None)
    if type(size) is not int or size not in ALLOWED_SP_SIZES:
        raise SAICTemporalActionOperatorError(
            "live Bernini Ulysses size must be production SP4 or test SP1"
        )
    if type(rank) is not int or not 0 <= rank < size:
        raise SAICTemporalActionOperatorError("live Bernini Ulysses rank is invalid")
    return rank, size


def _validate_full_source_branch(
    branch: Any, *, current_noisy_target: torch.Tensor
) -> native_pack.NativeRV2VBranch:
    if type(branch) is not native_pack.NativeRV2VBranch:
        raise SAICTemporalActionOperatorError(
            "online action operator requires an exact native NativeRV2VBranch"
        )
    if branch.name not in FULL_SOURCE_BRANCHES:
        raise SAICTemporalActionOperatorError(
            "online action operator accepts only full-source native V/VI branches"
        )
    try:
        online_motion._validate_current_state(  # noqa: SLF001 - shared contract
            current_noisy_target, label="current_noisy_target"
        )
    except online_motion.SAICOnlineMotionFieldError as error:
        raise SAICTemporalActionOperatorError(str(error)) from error
    target_tokens = branch.total_tokens - branch.condition_tokens
    height, width = map(int, current_noisy_target.shape[-2:])
    if height % 2 or width % 2:
        raise SAICTemporalActionOperatorError(
            "current state spatial geometry must be divisible by native patch size"
        )
    patch_positions = (height // 2) * (width // 2)
    expected_target_tokens = online_motion.LATENT_PHASES_EXACT81 * patch_positions
    if target_tokens != expected_target_tokens:
        raise SAICTemporalActionOperatorError(
            "native target suffix does not match current exact81 patch geometry"
        )
    if branch.name == "V":
        expected_condition_tokens = target_tokens
        expected_source_ids = native_pack.VI_VIDEO_SOURCE_IDS + (0.0,)
    else:
        expected_condition_tokens = (
            target_tokens + native_pack.REFERENCE_COUNT * patch_positions
        )
        expected_source_ids = (
            native_pack.VI_VIDEO_SOURCE_IDS
            + native_pack.VI_IMAGE_SOURCE_IDS
            + (0.0,)
        )
    if (
        branch.condition_tokens != expected_condition_tokens
        or branch.source_ids != expected_source_ids
        or branch.concat_order != native_pack.BRANCH_CONCAT_ORDER[branch.name]
        or type(branch.latents) is not torch.Tensor
        or branch.latents.ndim != 3
        or int(branch.latents.shape[0]) != 1
        or int(branch.latents.shape[1]) != branch.total_tokens
        or type(branch.target_mask) is not torch.Tensor
        or branch.target_mask.dtype != torch.bool
        or branch.target_mask.ndim != 1
        or int(branch.target_mask.numel()) != branch.total_tokens
        or branch.target_mask.device != branch.latents.device
        or branch.latents.device != current_noisy_target.device
    ):
        raise SAICTemporalActionOperatorError("native full-source branch closure differs")
    expected_mask = torch.zeros_like(branch.target_mask)
    expected_mask[branch.condition_tokens :] = True
    if not torch.equal(branch.target_mask, expected_mask):
        raise SAICTemporalActionOperatorError(
            "native branch target mask is not the exact noisy-target suffix"
        )
    return branch


def _derive_local_tensor(
    global_value: torch.Tensor, *, rank: int, size: int, pad_value: Any
) -> torch.Tensor:
    local_length = math.ceil(int(global_value.numel()) / size)
    padded_length = local_length * size
    if padded_length > int(global_value.numel()):
        global_value = F.pad(
            global_value,
            (0, padded_length - int(global_value.numel())),
            value=pad_value,
        )
    start = rank * local_length
    return global_value[start : start + local_length].clone().contiguous()


def sigma_gate(schedule_index: int) -> tuple[str, float]:
    if type(schedule_index) is not int or not 0 <= schedule_index < 40:
        raise SAICTemporalActionOperatorError("schedule index is outside exact40")
    if schedule_index < 33:
        return "high", 1.0
    if schedule_index < 38:
        return "mid", 0.5
    return "low_exact_base", 0.0


@dataclass(frozen=True)
class _TemporalRuntimeRoute:
    branch: native_pack.NativeRV2VBranch = field(repr=False, compare=False)
    scheduler: Any = field(repr=False, compare=False)
    timestep: torch.Tensor = field(repr=False, compare=False)
    current_noisy_target: torch.Tensor = field(repr=False, compare=False)
    motion_field: online_motion.SAICOnlineMotionField = field(
        repr=False, compare=False
    )
    parallel_state: Any = field(repr=False, compare=False)
    owner_token: Any = field(repr=False, compare=False)
    branch_name: str
    schedule_index: int
    sequence_parallel_rank: int
    sequence_parallel_size: int
    local_target_mask: torch.Tensor = field(repr=False, compare=False)
    local_phase_indices: torch.Tensor = field(repr=False, compare=False)
    _branch_latents_binding: tuple[Any, ...] = field(repr=False, compare=False)
    _branch_mask_binding: tuple[Any, ...] = field(repr=False, compare=False)
    _timestep_binding: tuple[Any, ...] = field(repr=False, compare=False)
    _current_state_binding: tuple[Any, ...] = field(repr=False, compare=False)
    _local_mask_binding: tuple[Any, ...] = field(repr=False, compare=False)
    _local_phase_binding: tuple[Any, ...] = field(repr=False, compare=False)
    _mint: Any = field(repr=False, compare=False)

    @property
    def gate_name(self) -> str:
        if self.motion_field.is_noop:
            return "noop_exact_base"
        return sigma_gate(self.schedule_index)[0]

    @property
    def gate_weight(self) -> float:
        if self.motion_field.is_noop:
            return 0.0
        return sigma_gate(self.schedule_index)[1]

    @property
    def operator_active(self) -> bool:
        return not self.motion_field.is_noop and self.gate_weight > 0.0

    def assert_live(self, *, owner_token: Any, transformer: nn.Module) -> None:
        if self._mint is not _ROUTE_MINT or owner_token is not self.owner_token:
            raise SAICTemporalActionOperatorError("online action route owner differs")
        _assert_gradient_checkpointing_disabled(transformer)
        branch = _validate_full_source_branch(
            self.branch, current_noisy_target=self.current_noisy_target
        )
        if branch.name != self.branch_name:
            raise SAICTemporalActionOperatorError("bound native branch role changed")
        _assert_tensor_binding(
            branch.latents, self._branch_latents_binding, label="branch latents"
        )
        _assert_tensor_binding(
            branch.target_mask, self._branch_mask_binding, label="native target mask"
        )
        _assert_tensor_binding(
            self.timestep, self._timestep_binding, label="forward timestep"
        )
        _assert_tensor_binding(
            self.current_noisy_target,
            self._current_state_binding,
            label="current noisy target",
        )
        try:
            self.motion_field.assert_live(
                current_noisy_target=self.current_noisy_target,
                scheduler=self.scheduler,
                timestep=self.timestep,
            )
        except online_motion.SAICOnlineMotionFieldError as error:
            raise SAICTemporalActionOperatorError(str(error)) from error
        if self.motion_field.schedule_index != self.schedule_index:
            raise SAICTemporalActionOperatorError("motion field sigma route changed")
        live_state = _get_live_parallel_state()
        rank, size = _parallel_coordinates(live_state)
        if (
            live_state is not self.parallel_state
            or rank != self.sequence_parallel_rank
            or size != self.sequence_parallel_size
        ):
            raise SAICTemporalActionOperatorError("bound live Ulysses route changed")
        _assert_tensor_binding(
            self.local_target_mask,
            self._local_mask_binding,
            label="derived local target mask",
        )
        _assert_tensor_binding(
            self.local_phase_indices,
            self._local_phase_binding,
            label="derived local phase indices",
        )
        if not torch.equal(self.local_target_mask, self.local_phase_indices >= 0):
            raise SAICTemporalActionOperatorError(
                "derived target selector and phase map differ"
            )

    def selector_and_phases(
        self, hidden_states: torch.Tensor, *, owner_token: Any, transformer: nn.Module
    ) -> tuple[torch.Tensor, torch.Tensor]:
        self.assert_live(owner_token=owner_token, transformer=transformer)
        if (
            type(hidden_states) is not torch.Tensor
            or hidden_states.ndim != 3
            or int(hidden_states.shape[0]) != 1
            or hidden_states.device != self.branch.latents.device
            or int(hidden_states.shape[1]) != int(self.local_target_mask.numel())
        ):
            raise SAICTemporalActionOperatorError(
                "hidden sequence differs from runtime-derived native SP shard"
            )
        return self.local_target_mask, self.local_phase_indices

    def receipt(self) -> Mapping[str, Any]:
        value = {
            "schema_version": SCHEMA_VERSION,
            "branch_name": self.branch_name,
            "schedule_index": self.schedule_index,
            "sigma_gate": self.gate_name,
            "sigma_gate_weight": self.gate_weight,
            "operator_active": self.operator_active,
            "sequence_parallel_rank": self.sequence_parallel_rank,
            "sequence_parallel_size": self.sequence_parallel_size,
            "local_rows": int(self.local_target_mask.numel()),
            "local_target_rows": int(self.local_target_mask.sum().item()),
            "phase_code_shape": [
                online_motion.LATENT_PHASES_EXACT81,
                online_motion.PHASE_CODE_DIM,
            ],
            "motion_field_receipt_digest": self.motion_field.receipt()["digest"],
            "mask_and_phase_derivation": (
                "native_target_suffix_phase_major_append_false_then_live_sp_slice"
            ),
            "caller_supplied_mask_rank_size_index_sigma_phase_or_code": False,
        }
        return {**value, "digest": _object_sha256(value)}


def _mint_runtime_route(
    *,
    branch: Any,
    scheduler: Any,
    timestep: torch.Tensor,
    current_noisy_target: torch.Tensor,
    motion_field: online_motion.SAICOnlineMotionField,
    transformer: nn.Module,
    owner_token: Any,
) -> _TemporalRuntimeRoute:
    _assert_gradient_checkpointing_disabled(transformer)
    if type(motion_field) is not online_motion.SAICOnlineMotionField:
        raise SAICTemporalActionOperatorError(
            "motion field must be minted by build_online_motion_field"
        )
    branch = _validate_full_source_branch(
        branch, current_noisy_target=current_noisy_target
    )
    if timestep.device != branch.latents.device:
        raise SAICTemporalActionOperatorError(
            "runtime timestep and native branch must share the forward device"
        )
    try:
        motion_field.assert_live(
            current_noisy_target=current_noisy_target,
            scheduler=scheduler,
            timestep=timestep,
        )
    except online_motion.SAICOnlineMotionFieldError as error:
        raise SAICTemporalActionOperatorError(str(error)) from error
    schedule_index = motion_field.schedule_index
    parallel_state = _get_live_parallel_state()
    rank, size = _parallel_coordinates(parallel_state)
    # Phase-major ordering is Bernini patch_vae_latent's [T,H/2,W/2]
    # flattening.  Source/reference/padding rows retain sentinel -1.
    target_tokens = branch.total_tokens - branch.condition_tokens
    patch_positions = target_tokens // online_motion.LATENT_PHASES_EXACT81
    global_phases = torch.cat(
        (
            torch.full(
                (branch.condition_tokens,),
                -1,
                dtype=torch.int64,
                device=branch.latents.device,
            ),
            torch.arange(
                online_motion.LATENT_PHASES_EXACT81,
                dtype=torch.int64,
                device=branch.latents.device,
            ).repeat_interleave(patch_positions),
        )
    )
    local_mask = _derive_local_tensor(
        branch.target_mask, rank=rank, size=size, pad_value=False
    )
    local_phases = _derive_local_tensor(
        global_phases, rank=rank, size=size, pad_value=-1
    )
    if not torch.equal(local_mask, local_phases >= 0):
        raise SAICTemporalActionOperatorError(
            "native target mask and exact81 phase map disagree"
        )
    route = _TemporalRuntimeRoute(
        branch=branch,
        scheduler=scheduler,
        timestep=timestep,
        current_noisy_target=current_noisy_target,
        motion_field=motion_field,
        parallel_state=parallel_state,
        owner_token=owner_token,
        branch_name=branch.name,
        schedule_index=schedule_index,
        sequence_parallel_rank=rank,
        sequence_parallel_size=size,
        local_target_mask=local_mask,
        local_phase_indices=local_phases,
        _branch_latents_binding=_tensor_binding(branch.latents),
        _branch_mask_binding=_tensor_binding(branch.target_mask),
        _timestep_binding=_tensor_binding(timestep),
        _current_state_binding=_tensor_binding(current_noisy_target),
        _local_mask_binding=_tensor_binding(local_mask),
        _local_phase_binding=_tensor_binding(local_phases),
        _mint=_ROUTE_MINT,
    )
    route.assert_live(owner_token=owner_token, transformer=transformer)
    return route


_ACTIVE_ROUTE: ContextVar[Optional[_TemporalRuntimeRoute]] = ContextVar(
    "bernini_saic_temporal_action_operator_v2_route", default=None
)


def active_route() -> Optional[_TemporalRuntimeRoute]:
    return _ACTIVE_ROUTE.get()


@contextmanager
def _activate_route(route: _TemporalRuntimeRoute) -> Iterator[None]:
    if type(route) is not _TemporalRuntimeRoute or route._mint is not _ROUTE_MINT:
        raise SAICTemporalActionOperatorError(
            "route was not minted from the live native runtime"
        )
    if active_route() is not None:
        raise SAICTemporalActionOperatorError("nested temporal action routes are forbidden")
    token: Token[Optional[_TemporalRuntimeRoute]] = _ACTIVE_ROUTE.set(route)
    try:
        yield
    finally:
        _ACTIVE_ROUTE.reset(token)


class SAICTemporalActionResidual(nn.Module):
    """Rank-8 hidden-state x online-phase-code target-row residual."""

    def __init__(
        self,
        base: nn.Module,
        *,
        projection: str,
        transformer: nn.Module,
        owner_token: Any,
    ) -> None:
        super().__init__()
        if not isinstance(base, nn.Linear):
            raise SAICTemporalActionOperatorError(f"{projection} base must be nn.Linear")
        if projection not in {"to_q", "to_out.0"}:
            raise SAICTemporalActionOperatorError(
                "only cross-attention Q/O may be wrapped"
            )
        if any(parameter.requires_grad for parameter in base.parameters()):
            raise SAICTemporalActionOperatorError(
                "wrapped base projection must be frozen"
            )
        self.base = base
        self.projection = projection
        self.rank = ACTION_OPERATOR_RANK
        self.state_down = nn.Linear(
            base.in_features, self.rank, bias=False, dtype=torch.float32
        )
        self.phase_gate = nn.Linear(
            online_motion.PHASE_CODE_DIM,
            self.rank,
            bias=False,
            dtype=torch.float32,
        )
        self.output_up = nn.Linear(
            self.rank, base.out_features, bias=False, dtype=torch.float32
        )
        nn.init.kaiming_uniform_(self.state_down.weight, a=math.sqrt(5.0))
        nn.init.kaiming_uniform_(self.phase_gate.weight, a=math.sqrt(5.0))
        nn.init.zeros_(self.output_up.weight)
        self._transformer_ref = weakref.ref(transformer)
        self._owner_token = owner_token

    @property
    def weight(self) -> Any:
        return self.base.weight

    @property
    def bias(self) -> Any:
        return self.base.bias

    def _transformer(self) -> nn.Module:
        transformer = self._transformer_ref()
        if transformer is None:
            raise SAICTemporalActionOperatorError(
                "installed transformer no longer exists"
            )
        return transformer

    def _route_geometry(
        self, hidden_states: torch.Tensor, route: _TemporalRuntimeRoute
    ) -> tuple[torch.Tensor, torch.Tensor]:
        return route.selector_and_phases(
            hidden_states,
            owner_token=self._owner_token,
            transformer=self._transformer(),
        )

    def _selected_delta(
        self,
        hidden_states: torch.Tensor,
        selector: torch.Tensor,
        phases: torch.Tensor,
        route: _TemporalRuntimeRoute,
    ) -> torch.Tensor:
        selected = hidden_states[:, selector, :]
        selected_phases = phases[selector]
        if bool((selected_phases < 0).any().item()):
            raise SAICTemporalActionOperatorError(
                "selected native target row has no exact81 phase"
            )
        with torch.autocast(device_type=hidden_states.device.type, enabled=False):
            phase_code = route.motion_field.phase_code.to(
                device=hidden_states.device, dtype=torch.float32
            ).index_select(0, selected_phases)
            state_feature = F.silu(self.state_down(selected.float()))
            motion_feature = torch.tanh(self.phase_gate(phase_code)).unsqueeze(0)
            delta = self.output_up(state_feature * motion_feature)
            delta = delta * route.gate_weight
        return delta.to(hidden_states.dtype)

    def adapter_delta(self, hidden_states: torch.Tensor) -> torch.Tensor:
        result = torch.zeros(
            (*hidden_states.shape[:-1], self.base.out_features),
            dtype=hidden_states.dtype,
            device=hidden_states.device,
        )
        route = active_route()
        if route is None:
            return result
        selector, phases = self._route_geometry(hidden_states, route)
        if not route.operator_active:
            return result
        result[:, selector, :] = self._selected_delta(
            hidden_states, selector, phases, route
        )
        return result

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        route = active_route()
        if route is not None:
            # Fail before even evaluating the base when runtime bindings drift.
            route.assert_live(
                owner_token=self._owner_token, transformer=self._transformer()
            )
        base = self.base(hidden_states)
        if route is None:
            return base
        selector, phases = self._route_geometry(hidden_states, route)
        # Semantically direct return: NaN adapter weights cannot contaminate a
        # no-op or either registered low-sigma step.
        if not route.operator_active:
            return base
        result = base.clone()
        result[:, selector, :] = base[:, selector, :] + self._selected_delta(
            hidden_states, selector, phases, route
        )
        return result


@dataclass
class SAICTemporalActionOperatorHandle:
    transformer: nn.Module
    q_wrappers: tuple[tuple[int, SAICTemporalActionResidual], ...]
    o_wrappers: tuple[tuple[int, SAICTemporalActionResidual], ...]
    original_q: tuple[tuple[int, nn.Module], ...]
    original_o: tuple[tuple[int, nn.Module], ...]
    original_patch_embedding_id: int
    protected_ids: tuple[tuple[int, ...], ...]
    owner_token: Any = field(repr=False)
    restored: bool = False

    def trainable_named_parameters(self) -> tuple[tuple[str, nn.Parameter], ...]:
        if self.restored:
            raise SAICTemporalActionOperatorError("temporal action operator was restored")
        rows: list[tuple[str, nn.Parameter]] = []
        for index, wrapper in self.q_wrappers:
            rows.extend(
                (
                    (f"blocks.{index}.attn2.to_q.state_down.weight", wrapper.state_down.weight),
                    (f"blocks.{index}.attn2.to_q.phase_gate.weight", wrapper.phase_gate.weight),
                    (f"blocks.{index}.attn2.to_q.output_up.weight", wrapper.output_up.weight),
                )
            )
        for index, wrapper in self.o_wrappers:
            rows.extend(
                (
                    (f"blocks.{index}.attn2.to_out.0.state_down.weight", wrapper.state_down.weight),
                    (f"blocks.{index}.attn2.to_out.0.phase_gate.weight", wrapper.phase_gate.weight),
                    (f"blocks.{index}.attn2.to_out.0.output_up.weight", wrapper.output_up.weight),
                )
            )
        if len(rows) != len(ACTION_BLOCK_INDICES) * 6:
            raise SAICTemporalActionOperatorError("trainable key count differs")
        if len({id(parameter) for _, parameter in rows}) != len(rows):
            raise SAICTemporalActionOperatorError("trainable parameter alias detected")
        if any(
            parameter.dtype != torch.float32 or not parameter.requires_grad
            for _, parameter in rows
        ):
            raise SAICTemporalActionOperatorError("trainable parameter gauge differs")
        return tuple(rows)

    def base_parameters_frozen(self) -> bool:
        trainable_ids = {
            id(parameter) for _, parameter in self.trainable_named_parameters()
        }
        observed = {
            id(parameter)
            for parameter in self.transformer.parameters()
            if parameter.requires_grad
        }
        return observed == trainable_ids

    def scope_untouched(self) -> bool:
        blocks = tuple(getattr(self.transformer, "blocks", ()))
        return (
            len(blocks) == TOTAL_BLOCKS_1P3B
            and _capture_protected_ids(blocks) == self.protected_ids
            and id(getattr(self.transformer, "patch_embedding", None))
            == self.original_patch_embedding_id
        )

    @contextmanager
    def route(
        self,
        *,
        branch: native_pack.NativeRV2VBranch,
        scheduler: Any,
        timestep: torch.Tensor,
        current_noisy_target: torch.Tensor,
        motion_field: online_motion.SAICOnlineMotionField,
    ) -> Iterator[_TemporalRuntimeRoute]:
        """Mint a route without accepting mask/rank/index/sigma/code metadata."""

        if self.restored:
            raise SAICTemporalActionOperatorError(
                "cannot route a restored temporal action operator"
            )
        route = _mint_runtime_route(
            branch=branch,
            scheduler=scheduler,
            timestep=timestep,
            current_noisy_target=current_noisy_target,
            motion_field=motion_field,
            transformer=self.transformer,
            owner_token=self.owner_token,
        )
        with _activate_route(route):
            try:
                yield route
            finally:
                route.assert_live(
                    owner_token=self.owner_token, transformer=self.transformer
                )

    def state_dict_for_save(self) -> Mapping[str, torch.Tensor]:
        state = {
            name: parameter.detach().float().cpu().contiguous().clone()
            for name, parameter in self.trainable_named_parameters()
        }
        if not state or any(not bool(value.isfinite().all()) for value in state.values()):
            raise SAICTemporalActionOperatorError(
                "trainable state must be nonempty finite CPU FP32"
            )
        return state

    def receipt(self) -> Mapping[str, Any]:
        trainable = self.trainable_named_parameters()
        value = {
            "schema_version": SCHEMA_VERSION,
            "classification": CLASSIFICATION,
            "blocks": list(ACTION_BLOCK_INDICES),
            "projections": ["attn2.to_q", "attn2.to_out.0"],
            "operator": (
                "up(silu(state_down(hidden))*tanh(phase_gate(online_code[phase])))"
            ),
            "rank": ACTION_OPERATOR_RANK,
            "phase_code_dimension": online_motion.PHASE_CODE_DIM,
            "phase_count_exact81": online_motion.LATENT_PHASES_EXACT81,
            "fp32_bias_free_trainable": True,
            "output_up_zero_initialized_at_install": True,
            "full_source_native_branches": list(FULL_SOURCE_BRANCHES),
            "active_sigma_indices": list(ACTIVE_SIGMA_INDICES),
            "low_sigma_indices_exact_base": list(LOW_SIGMA_EXACT_BASE_INDICES),
            "target_phase_map_from_native_suffix": True,
            "source_reference_padding_rows_exact_base": True,
            "route_accepts_mask_rank_size_index_sigma_phase_or_code": False,
            "route_binds_current_state_live_sp_native_mask_actual_sigma": True,
            "training_and_inference_route_identical": True,
            "action_id_consumed": False,
            "t2v_media_or_proposal_consumed": False,
            "mask_pose_flow_track_or_trajectory_consumed": False,
            "base_parameters_frozen": self.base_parameters_frozen(),
            "only_registered_cross_attention_qo_replaced": self.scope_untouched(),
            "patch_embedding_untouched": id(self.transformer.patch_embedding)
            == self.original_patch_embedding_id,
            "trainable_key_sha256": _object_sha256(sorted(name for name, _ in trainable)),
            "optimizer_created": False,
            "training_authorized": False,
            "semantic_action_success_claim": False,
        }
        return {**value, "digest": _object_sha256(value)}

    def restore(self) -> None:
        if self.restored or active_route() is not None:
            raise SAICTemporalActionOperatorError(
                "temporal action operator cannot be restored now"
            )
        if not self.scope_untouched():
            raise SAICTemporalActionOperatorError(
                "temporal action protected model scope changed"
            )
        blocks = tuple(self.transformer.blocks)
        for index, original in self.original_q:
            blocks[index].attn2.to_q = original
        for index, original in self.original_o:
            blocks[index].attn2.to_out[0] = original
        self.restored = True


def _capture_protected_ids(
    blocks: tuple[nn.Module, ...]
) -> tuple[tuple[int, ...], ...]:
    rows: list[tuple[int, ...]] = []
    for index, block in enumerate(blocks):
        attn1 = getattr(block, "attn1", None)
        attn2 = getattr(block, "attn2", None)
        self_out = getattr(attn1, "to_out", None)
        cross_out = getattr(attn2, "to_out", None)
        if (
            attn1 is None
            or attn2 is None
            or not isinstance(self_out, nn.ModuleList)
            or len(self_out) != 2
            or not isinstance(cross_out, nn.ModuleList)
            or len(cross_out) != 2
            or getattr(attn1, "to_q", None) is None
            or getattr(attn1, "to_k", None) is None
            or getattr(attn1, "to_v", None) is None
            or getattr(attn2, "to_q", None) is None
            or getattr(attn2, "to_k", None) is None
            or getattr(attn2, "to_v", None) is None
        ):
            raise SAICTemporalActionOperatorError(
                f"block {index} native attention structure differs"
            )
        row = [
            id(attn1),
            id(attn1.to_q),
            id(attn1.to_k),
            id(attn1.to_v),
            id(self_out[0]),
            id(self_out[1]),
            id(attn2),
            id(attn2.to_k),
            id(attn2.to_v),
            id(cross_out[1]),
        ]
        if index not in ACTION_BLOCK_INDICES:
            row.extend((id(attn2.to_q), id(cross_out[0])))
        rows.append(tuple(row))
    return tuple(rows)


def install_saic_temporal_action_operator(
    transformer: nn.Module,
) -> SAICTemporalActionOperatorHandle:
    """Install the zero-initialized online phase operator on early cross-Q/O."""

    if not isinstance(transformer, nn.Module):
        raise SAICTemporalActionOperatorError("transformer must be nn.Module")
    _assert_gradient_checkpointing_disabled(transformer)
    if any(parameter.requires_grad for parameter in transformer.parameters()):
        raise SAICTemporalActionOperatorError(
            "freeze the complete Bernini transformer before operator installation"
        )
    blocks = tuple(getattr(transformer, "blocks", ()))
    patch = getattr(transformer, "patch_embedding", None)
    if (
        len(blocks) != TOTAL_BLOCKS_1P3B
        or not isinstance(patch, nn.Conv3d)
        or not callable(getattr(transformer, "patch_vae_latent", None))
    ):
        raise SAICTemporalActionOperatorError(
            "Bernini-R 1.3B native transformer structure differs"
        )
    hidden = int(patch.out_channels)
    protected_ids = _capture_protected_ids(blocks)
    original_q: list[tuple[int, nn.Module]] = []
    original_o: list[tuple[int, nn.Module]] = []
    for index in ACTION_BLOCK_INDICES:
        attention = getattr(blocks[index], "attn2", None)
        query = getattr(attention, "to_q", None)
        output = getattr(attention, "to_out", None)
        if (
            not isinstance(query, nn.Linear)
            or not isinstance(output, nn.ModuleList)
            or len(output) != 2
            or not isinstance(output[0], nn.Linear)
            or query.in_features != hidden
            or query.out_features != hidden
            or output[0].in_features != hidden
            or output[0].out_features != hidden
        ):
            raise SAICTemporalActionOperatorError(
                f"block {index} native cross-attention Q/O differs"
            )
        original_q.append((index, query))
        original_o.append((index, output[0]))

    owner_token = object()
    device = patch.weight.device
    q_wrappers: list[tuple[int, SAICTemporalActionResidual]] = []
    o_wrappers: list[tuple[int, SAICTemporalActionResidual]] = []
    try:
        for (index, query), (_, output) in zip(original_q, original_o):
            q_wrapper = SAICTemporalActionResidual(
                query,
                projection="to_q",
                transformer=transformer,
                owner_token=owner_token,
            ).to(device=device)
            o_wrapper = SAICTemporalActionResidual(
                output,
                projection="to_out.0",
                transformer=transformer,
                owner_token=owner_token,
            ).to(device=device)
            blocks[index].attn2.to_q = q_wrapper
            blocks[index].attn2.to_out[0] = o_wrapper
            q_wrappers.append((index, q_wrapper))
            o_wrappers.append((index, o_wrapper))
    except Exception:
        for index, original in original_q:
            blocks[index].attn2.to_q = original
        for index, original in original_o:
            blocks[index].attn2.to_out[0] = original
        raise

    handle = SAICTemporalActionOperatorHandle(
        transformer=transformer,
        q_wrappers=tuple(q_wrappers),
        o_wrappers=tuple(o_wrappers),
        original_q=tuple(original_q),
        original_o=tuple(original_o),
        original_patch_embedding_id=id(patch),
        protected_ids=protected_ids,
        owner_token=owner_token,
    )
    receipt = handle.receipt()
    if (
        receipt["base_parameters_frozen"] is not True
        or receipt["only_registered_cross_attention_qo_replaced"] is not True
        or receipt["patch_embedding_untouched"] is not True
    ):
        handle.restore()
        raise SAICTemporalActionOperatorError("operator installation scope failed")
    return handle


__all__ = [
    "ACTION_BLOCK_INDICES",
    "ACTION_OPERATOR_RANK",
    "ACTIVE_SIGMA_INDICES",
    "CLASSIFICATION",
    "FULL_SOURCE_BRANCHES",
    "LOW_SIGMA_EXACT_BASE_INDICES",
    "SAICTemporalActionOperatorError",
    "SAICTemporalActionOperatorHandle",
    "SAICTemporalActionResidual",
    "SCHEMA_VERSION",
    "TOTAL_BLOCKS_1P3B",
    "active_route",
    "install_saic_temporal_action_operator",
    "sigma_gate",
]
